-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 15:57:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Manage Research
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Manage Research
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Manage Research` DEFAULT CHARACTER SET utf8 ;
USE `Manage Research` ;

-- -----------------------------------------------------
-- Table `Manage Research`.`Award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Manage Research`.`Award` (
  `Award_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Grant_Award` VARCHAR(45) NOT NULL,
  `Year` DATE NOT NULL,
  `Paper_ID` INT NOT NULL,
  PRIMARY KEY (`Award_ID`, `Paper_ID`),
  INDEX `fk_Giai_thuong_De_tai1_idx` (`Paper_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Giai_thuong_De_tai1`
    FOREIGN KEY (`Paper_ID`)
    REFERENCES `Manage Research`.`Research` (`Paper_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manage Research`.`Lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Manage Research`.`Lecturer` (
  `Lecturer_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  `Faculty` VARCHAR(45) NOT NULL,
  `Research_Field` VARCHAR(45) NULL,
  PRIMARY KEY (`Lecturer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manage Research`.`Research`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Manage Research`.`Research` (
  `Paper_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Research_Field` VARCHAR(45) NOT NULL,
  `Summary` VARCHAR(1000) NOT NULL,
  `Year` DATE NOT NULL,
  `Faculty` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Paper_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manage Research`.`Research_Lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Manage Research`.`Research_Lecturer` (
  `Lecturer_ID` INT NOT NULL,
  `Paper_ID` INT NOT NULL,
  PRIMARY KEY (`Lecturer_ID`, `Paper_ID`),
  INDEX `fk_Giang_vien_huong_dan_has_De_tai_De_tai1_idx` (`Paper_ID` ASC) VISIBLE,
  INDEX `fk_Giang_vien_huong_dan_has_De_tai_Giang_vien_huong_dan_idx` (`Lecturer_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Giang_vien_huong_dan_has_De_tai_Giang_vien_huong_dan0`
    FOREIGN KEY (`Lecturer_ID`)
    REFERENCES `Manage Research`.`Lecturer` (`Lecturer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Giang_vien_huong_dan_has_De_tai_De_tai10`
    FOREIGN KEY (`Paper_ID`)
    REFERENCES `Manage Research`.`Research` (`Paper_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manage Research`.`Research_Participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Manage Research`.`Research_Participant` (
  `Paper_ID` INT NOT NULL,
  `Student_ID` INT NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Paper_ID`, `Student_ID`),
  INDEX `fk_De_tai_has_Sinh_vien_Sinh_vien1_idx` (`Paper_ID` ASC) VISIBLE,
  INDEX `fk_De_tai_has_Sinh_vien_De_tai1_idx` (`Student_ID` ASC) VISIBLE,
  CONSTRAINT `fk_De_tai_has_Sinh_vien_De_tai1`
    FOREIGN KEY (`Student_ID`)
    REFERENCES `Manage Research`.`Research` (`Paper_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_De_tai_has_Sinh_vien_Sinh_vien1`
    FOREIGN KEY (`Paper_ID`)
    REFERENCES `Manage Research`.`Student` (`Student_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manage Research`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Manage Research`.`Student` (
  `Student_ID` INT NOT NULL AUTO_INCREMENT,
  `Full_name` VARCHAR(45) NOT NULL,
  `Class` VARCHAR(45) NOT NULL,
  `Major` VARCHAR(45) NOT NULL,
  `Faculty` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Student_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
